//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryPricelist
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int LineTypeID { get; set; }
        public Nullable<decimal> InstallationCost { get; set; }
        public Nullable<decimal> MonthlyCharges { get; set; }
        public Nullable<decimal> Internet { get; set; }
        public Nullable<decimal> MSN { get; set; }
        public Nullable<bool> PaymentIsForWholeMonth { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual LineTypes LineTypes { get; set; }
    }
}
