//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.CountryPricelist = new HashSet<CountryPricelist>();
            this.Orders = new HashSet<Orders>();
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int ID { get; set; }
        public string Name1GR { get; set; }
        public string Name1EN { get; set; }
        public string Name2GR { get; set; }
        public string Name2EN { get; set; }
        public int CountryID { get; set; }
        public string ZIPCoode { get; set; }
        public string CityGR { get; set; }
        public string CityEN { get; set; }
        public string ChargeTelephone { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string FAX1 { get; set; }
        public string FAX2 { get; set; }
        public string Address1GR { get; set; }
        public string Address1EN { get; set; }
        public string Address2GR { get; set; }
        public string Address2EN { get; set; }
        public string ContactPersonGR { get; set; }
        public string ContactPersonEN { get; set; }
        public int CustomerTypeID { get; set; }
        public int LanguageID { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string AFM { get; set; }
        public string DOY { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsProvider { get; set; }
    
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryPricelist> CountryPricelist { get; set; }
        public virtual CustomerTypes CustomerTypes { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
