//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountLine
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public int JobID { get; set; }
        public Nullable<decimal> TasksAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public bool Applied { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual Jobs Jobs { get; set; }
    }
}
