//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentReplacemets
    {
        public int ID { get; set; }
        public string UniqueName { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Type { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public string BookmarkTitle { get; set; }
        public string DocumentPart { get; set; }
    }
}
