//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.Tasks = new HashSet<Tasks>();
            this.JobCancelPrices = new HashSet<JobCancelPrices>();
            this.JobFormulas = new HashSet<JobFormulas>();
            this.DiscountLine = new HashSet<DiscountLine>();
            this.TasksLine = new HashSet<TasksLine>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinimumTime { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<int> SalesID { get; set; }
        public int JobsMainID { get; set; }
        public int JobTypesID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
        public virtual Sales Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCancelPrices> JobCancelPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobFormulas> JobFormulas { get; set; }
        public virtual JobsMain JobsMain { get; set; }
        public virtual JobTypes JobTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountLine> DiscountLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksLine> TasksLine { get; set; }
    }
}
