//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersPTSGR2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersPTSGR2()
        {
            this.TasksPTSGR = new HashSet<TasksPTSGR>();
        }
    
        public int ID { get; set; }
        public int OrdersPTSGRID { get; set; }
        public int CountryID { get; set; }
        public int ProviderID { get; set; }
        public string RegNo { get; set; }
        public string InvoiceProtocol { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual OrdersPTSGR OrdersPTSGR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksPTSGR> TasksPTSGR { get; set; }
    }
}
