//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersPTSGR
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int CountryID { get; set; }
        public int CustomerID { get; set; }
        public string RegNo { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
