//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTSGRPricelist
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal InstallationCost { get; set; }
        public decimal ChargesPerMonth { get; set; }
        public decimal ChargesPerDay { get; set; }
        public bool SupportsMSN { get; set; }
        public bool IsChargePerMonth { get; set; }
        public Nullable<decimal> MSNPerMonth { get; set; }
        public Nullable<decimal> MSNPerDay { get; set; }
    }
}
