//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesFormulas
    {
        public int ID { get; set; }
        public int SalesID { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public decimal SalePercent { get; set; }
    
        public virtual Sales Sales { get; set; }
    }
}
