//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTERT_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string RegNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> RequestedPositionID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string PlaceFrom { get; set; }
        public string PlaceTo { get; set; }
        public Nullable<int> PlaceDistanceKm { get; set; }
        public Nullable<System.DateTime> DateTimeStartOrder { get; set; }
        public Nullable<System.DateTime> DateTimeEndOrder { get; set; }
        public int DateTimeDurationOrder { get; set; }
        public Nullable<bool> IsDurationInDays { get; set; }
        public Nullable<System.DateTime> DateTimeStartActual { get; set; }
        public Nullable<System.DateTime> DateTimeEndActual { get; set; }
        public Nullable<int> DateTimeDurationActual { get; set; }
        public Nullable<decimal> CostCalculated { get; set; }
        public Nullable<bool> InstallationCharges { get; set; }
        public Nullable<bool> MonthlyCharges { get; set; }
        public Nullable<decimal> CallCharges { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<decimal> TechnicalSupport { get; set; }
        public Nullable<decimal> AddedCharges { get; set; }
        public Nullable<decimal> CostActual { get; set; }
        public Nullable<System.DateTime> PaymentDateOrder { get; set; }
        public Nullable<System.DateTime> PaymentDateCalculated { get; set; }
        public Nullable<System.DateTime> PaymentDateActual { get; set; }
        public Nullable<bool> IsForHelpers { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<decimal> CancelPrice { get; set; }
        public string Comments { get; set; }
        public string InvoceComments { get; set; }
        public Nullable<int> SateliteID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Jobs Jobs { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual RequestedPositions RequestedPositions { get; set; }
        public virtual Satelites Satelites { get; set; }
    }
}
